apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-web2
  labels:
    app: hello-web-apps2
spec:
  replicas: 2
  selector:
    matchLabels:
      project: kgb2
  template:
    metadata:
      labels:
        project: kgb2
    spec:
      containers:
        - name: kgb-web2
          image: elferey/docker_images:noactuator
          ports:
            - containerPort: 9092
          readinessProbe:
            httpGet:
              path: /actuator
              port: 9092
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 9092
              scheme: HTTP
            timeoutSeconds: 5
            periodSeconds: 10
            failureThreshold: 6
          startupProbe:
            httpGet:
              path: /actuator/metrics
              port: 9092
              scheme: HTTP
            periodSeconds: 5
            failureThreshold: 36
---

apiVersion: v1
kind: Service
metadata:
  name: my-service2
  labels:
    env: prod
spec:
  selector:
    project: kgb2
  ports:
    - name: app-listener2
      protocol: TCP
      port: 8080
      targetPort: 9092
  type: LoadBalancer

---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: auto2
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: hello-web2
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 90
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70
